### ISSUE TITLE
The list was removed from Wikipedia

### ISSUE THREAD

**Issue by billcastillo** [sorxrob/coronavirus-ph-api#1]
API not working anymore
https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_the_Philippines#Cases

**Comment by sorxrob** [comment]
Thank you for the update. That' sad. Will update the list.

**Comment by Oceaneyes123** [comment]
Not working on me too :(

**Comment by sorxrob** [comment]
> Not working on me too :(

It'll be available in less than 2 hours again. I'm getting data from another source, which is better and has more data.

**Comment by sorxrob** [comment]
It's up! thanks

**Comment by billcastillo** [comment]
The list was placed backed in Wikipedia. This just means Wikipedia isn't reliable

**Comment by sorxrob** [comment]
> The list was placed backed in Wikipedia. This just means Wikipedia isn't reliable

Yeah. I've updated it to get the list again from Wikipedia, then if it's unavailable, it'll get the reddit spreadsheet.
