### ISSUE TITLE
502: BAD_GATEWAY in lockdowns

### ISSUE THREAD

**Issue by jpjpjp28** [sorxrob/coronavirus-ph-api#11]
A Bad gateway returns when calling "/lockdowns" endpoint.

502: BAD_GATEWAY 
Code: NO_STATUS_CODE_FROM_FUNCTION 
ID: tpe1:7q4k5-1585190782029-8bcccc6a68cd

**Comment by sorxrob** [comment]
Fixed, thanks again!

**Comment by jpjpjp28** [comment]
Hi! This issue is showing again. Kindly reopen this issue.

**Comment by sorxrob** [comment]
Thank you. Fixed

**Comment by sorxrob** [comment]
Reopened. Will close if it's stable for a week.

**Comment by jpjpjp28** [comment]
Will close this issue since the lockdowns has been removed already.
