### ISSUE TITLE
Add total number of PUI

### ISSUE THREAD

**Issue by la-colinares** [sorxrob/coronavirus-ph-api#12]
Hello Sir,

Is it possible to add the number of PUI and their address?

Thank you.

**Comment by vanvictorlim** [comment]
Can you share reliable data source/s? Hopefully, both PUIs and PUMs.

**Comment by sorxrob** [comment]
You can get PUI's here https://coronavirus-ph-api.herokuapp.com/facilities

**Comment by la-colinares** [comment]
Thank you Sir!

**Comment by claide** [comment]
@sorxrob , tried to get total of puis but got 382 currently. Is this correct?
by the way thanks to this api
