### ISSUE TITLE
Case number 672 is doubled in the list of cases

### ISSUE THREAD

**Issue by jpjpjp28** [sorxrob/coronavirus-ph-api#13]
My app is throwing an IndexOutOfBoundsException when loading the list of cases. I found out that the list from the response has added one more index to the list which is the case number 672 being doubled (index 671 and 672).

**Comment by sorxrob** [comment]
Good catch! Fixed. Looks like the source mistakenly duplicated it.

**Comment by jpjpjp28** [comment]
Thanks for the fixes mate. Been filing a lot of issues since yesterday, sorry haha. So far there's no more issues, hope I didn't skipped anything. I'm done with the app, just polishing it and will upload it to Google Play. Will inform you once it's up already. Thanks!
