### ISSUE TITLE
[ERROR] 502: BAD_GATEWAY

### ISSUE THREAD

**Issue by luigel** [sorxrob/coronavirus-ph-api#14]
Hi. I just used this api but it returns a `502: BAD_GATEWAY` error. Please refer to the picture below.

[https://coronavirus-ph-api.now.sh/cases](https://coronavirus-ph-api.now.sh/cases)

![image](https://user-images.githubusercontent.com/26235960/77731456-eecdc480-703d-11ea-9206-58d876757408.png)

By the way thank you for providing this api :)

**Comment by sorxrob** [comment]
Ref #11

**Comment by jpjpjp28** [comment]
This is currently getting unstable. Sometimes I get this 502 error when loading the URL in the browser and sometimes it works. Tried reloading it a couple of times from the browser and my app and sometimes the 502 error shows up.

This screenshot was taken today:
<img width="1680" alt="Screen Shot 2020-03-29 at 6 00 41 PM" src="https://user-images.githubusercontent.com/9314473/77846248-43607380-71e7-11ea-8b50-60c7b500dfb5.png">

**Comment by sorxrob** [comment]
I'm trying to contact the provider and will upgrade my plan. Sorry for the inconvenience.

**Comment by jpjpjp28** [comment]
I see. Would it take much time? I already posted my App publicly earlier 😅

https://www.facebook.com/ryoma20/posts/2904201579720866

**Comment by sorxrob** [comment]
Im planning to deploy it on another domain. Ill keep you posted. Sorry

**Comment by sorxrob** [comment]
Sorry. I wont move it. Im waiting for zeit's response regarding my upgrade.

**Comment by sorxrob** [comment]
Removed my comments. While waiting for the provider's response, you'll temporarily get yesterday's case data. Sorry for the inconvenience!

**Comment by sorxrob** [comment]
Hi, switched to heroku https://coronavirus-ph-api.herokuapp.com/
