### ISSUE TITLE
Cases Outside Philippines - Wrong Response

### ISSUE THREAD

**Issue by jpjpjp28** [sorxrob/coronavirus-ph-api#15]
When calling "/cases-outside-ph" endpoint, the "country_territory_place" shows index instead of the name of the country. Also, the confirmed and died value are null.

**Comment by sorxrob** [comment]
Thanks, fixed.

**Comment by jpjpjp28** [comment]
It seems like this error shows again on the new URL. Kindly re-open it again.

**Comment by jpjpjp28** [comment]
Hi! The response looks different now as it shows the continental statistics instead of countries.

**Comment by jpjpjp28** [comment]
Hi Sir Robert. Any updates on this?
