### ISSUE TITLE
Confirmed Cases Value in Test Results is Null

### ISSUE THREAD

**Issue by jpjpjp28** [sorxrob/coronavirus-ph-api#17]
"confirmed_cases" value is null. Please see below the response of "/test-results" endpoint. 

`{"confirmed_cases":null,"cases_tested_negative":920,"cases_pending_test_results":667}`

**Comment by sorxrob** [comment]
Thank you jp! Fixed.

**Comment by vanvictorlim** [comment]
/services/Scraper.js  line 130
```
// We do this because infobox confirmed cases
// get updated quickly but the table hasn't
```  
Figuring out, what is infobox?
