### ISSUE TITLE
Null values in Cases outside PH

### ISSUE THREAD

**Issue by jpjpjp28** [sorxrob/coronavirus-ph-api#20]
There are null values showing up in the response of "/cases-outside-ph". 

There is also a value of "FC No." in "country_territory_place" key.

**Comment by sorxrob** [comment]
Hey, thank you thank you.

I'll update the logic on my free time so we don't have to deal with problems like this. Thanks jp!

**Comment by jpjpjp28** [comment]
No worries. Thanks too. I've already edited my post to let users know that we are encountering some issues temporarily and will keep them posted.

**Comment by sorxrob** [comment]
Hi @jpjpjp28 !

I switched to heroku already.  https://coronavirus-ph-api.herokuapp.com/

**Comment by jpjpjp28** [comment]
Hi! Just read your commits and changes earlier and I am planning to migrate it soon. But is there any possibilities of retaining the previous one for those existing users? As of now, all the mobile app doesn't have any means of letting all the users know that there's an update since it is not downloaded through Google Play and there's no built-in updater.

**Comment by sorxrob** [comment]
That's a really good question. Might as well keep it. Okay.
