### ISSUE TITLE
Cases response: Null value

### ISSUE THREAD

**Issue by jpjpjp28** [sorxrob/coronavirus-ph-api#23]
Hi Sir! The "case_no" value is null from the "/cases" number.

**Comment by sorxrob** [comment]
I think the author is updating data... let's see

**Comment by jpjpjp28** [comment]
I see. That is noted. It seems like the indices is wrong again as I am receiving an IndexOutOfBoundsException. There might me a double indices again I think.

**Comment by sorxrob** [comment]
Will work on this this coming weekend. Anyway, reddit cases as backup for now

**Comment by jpjpjp28** [comment]
By the way, are you using the same database as this https://covid19ph.com/? The developer of it said he is also using the data from the same thread in reddit but it seems like his data is more updated 🤔 Like from the number of deaths, the response of this API is 71 while his and the DOH is already 78. Also the information of the latest case of his data has already dates, ages, nationalities. Just curious about that.

**Comment by sorxrob** [comment]
No, but Im interested in where are they getting their data too. I might go with that

**Comment by jpjpjp28** [comment]
Anyway, your API is great and will continue using this. Though I might change my source in "confirmed", "recovered" and "deaths" (number of) to John Hopkins University Center temporarily.

**Comment by sorxrob** [comment]
Hi! The API is updated with more reliable data. Plus, added new /facilities endpoint.

**Comment by jpjpjp28** [comment]
Wow great job! And I think this issue is now gone, I double checked it. Thank you!
