### ISSUE TITLE
Some endpoints may be outdated

### ISSUE THREAD

**Issue by michaeljarizala** [sorxrob/coronavirus-ph-api#29]
Hi there,

First off, nice touch on the APIs. I see these endpoints are programmatically handled based off the gsheets and other sources from DOH, great stuff!

As already pointed out by others, some endpoints may be outdated. So, I would just like to ask:

1. Do all your sources come from DOH? Specially on _**/lockdowns**_ endpoint, I see CARAGA is still projected with 0 cases. But I'm from here and we have 2 current cases. If not, could you provide other relevant sources we can use? Google sheets, CSVs, API endpoints, etc.

2. Will all endpoints still be reliable for data presentation in the days to come? What endpoints may be possibly deemed deprecated?

I am using also other sources e.g.:
https://corona.lmao.ninja/v2/all
https://corona.lmao.ninja/v2/countries/PH
https://corona-api.com/countries/ph

Thanks!

**Comment by sorxrob** [comment]
Hello!

I'm currently updating the APIs and will do a commit tomorrow or tonight.
Data will be coming from DOH already.

Thank you.

**Comment by michaeljarizala** [comment]
Awesome! You rock! 🤘

Thanks a heap!
