### ISSUE TITLE
Places became numbers in Cases Outside PH

### ISSUE THREAD

**Issue by jpjpjp28** [sorxrob/coronavirus-ph-api#30]
All the "country_territory_place" became numbers instead of places. See sample response below:

`
[
  {
    "country_territory_place": "1",
    "confirmed": null,
    "recovered": 38,
    "died": null
  },
  {
    "country_territory_place": "2",
    "confirmed": null,
    "recovered": 44,
    "died": null
  }
]
`

Also confirmed and died are all null.

**Comment by sorxrob** [comment]
Hi JP!

I'm updating the APIs with new, more reliable data and will commit tomorrow.
