### ISSUE TITLE
Cases Endpoint: Cannot redefine property: For validation

### ISSUE THREAD

**Issue by jpjpjp28** [sorxrob/coronavirus-ph-api#37]
Calling "/cases" endpoint shows error.

`{
  "sucess": false,
  "message": "Cannot redefine property: For validation"
}`

**Comment by jsafe00** [comment]
> Calling "/cases" endpoint shows error.
> 
> `{ "sucess": false, "message": "Cannot redefine property: For validation" }`

I think this is already working now. The problem was the header title in the cases tab of the excel file.
