### ISSUE TITLE
502: BAD_GATEWAY

### ISSUE THREAD

**Issue by dertrockx** [sorxrob/coronavirus-ph-api#5]
I was using your API when suddenly it went 502. Here's the image of the error. Thank you
![502 error](https://user-images.githubusercontent.com/19862244/77510647-3facb400-6eaa-11ea-9181-9fb27b9a9777.PNG)

**Comment by sorxrob** [comment]
Hi thanks for this, may I know which specific route you are accessing?

**Comment by sorxrob** [comment]
Pushed an update, can you check again?

**Comment by dertrockx** [comment]
Hello, just checked out again. It's working now :) Thank you
btw, the endpoint I was using was the /cases endpoint.
